# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Third Party Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}

    strategy:
        fail-fast: False
        matrix:
          config:
            - {repo: "sphinx-toolbox/default_values", name: "default_values", version: "0.6.0"}
            - {repo: "sphinx-toolbox/dict2css", name: "dict2css", version: "0.3.0"}
            - {repo: "sphinx-toolbox/extras_require", name: "extras_require", version: "0.5.0"}
            - {repo: "sphinx-toolbox/seed_intersphinx_mapping", name: "seed_intersphinx_mapping", version: "1.2.2"}
            - {repo: "sphinx-toolbox/sphinx-debuginfo", name: "sphinx-debuginfo", version: "0.2.2"}
            - {repo: "sphinx-toolbox/sphinx-highlights", name: "sphinx-highlights", version: "0.6.0"}
            - {repo: "sphinx-toolbox/sphinx-toolbox", name: "sphinx-toolbox", version: "3.8.1"}
            - {repo: "sphinx-toolbox/toctree_plus", name: "toctree_plus", version: "0.8.0"}
            - {repo: "repo-helper/mkrecipe", name: "mkrecipe", version: "0.9.0"}
            - {repo: "repo-helper/whey", name: "whey", version: "0.1.1"}
            - {repo: "domdfcoding/consolekit", name: "consolekit", version: "1.7.1"}
            - {repo: "domdfcoding/mathematical", name: "mathematical", version: "0.5.1"}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v4"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.8"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: env
          conda-build-version: 3.28.4
          miniconda-version: py311_24.1.2-0
          python-version: "3.11"
          miniforge-variant: Mambaforge

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda config --add channels domdfcoding

      - name: "Build ${{ matrix.config.name }}"
        run: |
          git clone https://github.com/${{ matrix.config.repo }} ${{ matrix.config.name }}
          git -C $(pwd)/${{ matrix.config.name }} checkout v${{ matrix.config.version }}
          python -m whey --builder whey_conda --out-dir ${{ matrix.config.name }}/conda-bld/noarch ${{ matrix.config.name }}

          $CONDA/bin/conda index ./${{ matrix.config.name }}/conda-bld || exit 1
          $CONDA/bin/conda install -c file://$(pwd)/${{ matrix.config.name }}/conda-bld ${{ matrix.config.name }}=${{ matrix.config.version }} -y || exit 1
          $CONDA/bin/conda install pytest coincidence || exit 1
          pip install -r ${{ matrix.config.name }}/tests/requirements.txt || exit 1
          pytest ${{ matrix.config.name }}/tests || exit 1
